name: Release
# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron: "0 */6 * * *"
on: [push]

jobs:
 
  build:
    
    runs-on: ${{matrix.os}}-latest
    
    strategy:
      fail-fast: false
      matrix:
        node: [14]
        os: [windows]

    steps:
      - name: init
        uses: actions/checkout@v2
      
      - name: set node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      
      - run: node -v
      
#       - run: npm i -g gulp-cli@latest

#       - name: get sha
#         id: sha
#         shell: bash
#         run: echo "::set-output name=value::$(cat sha.txt)"

      - name: clone
        env:
          sha: ${{steps.sha.outputs.value}} 
        run: |
          ls -alF
          rm -rf *
          rm -rf .git
          rm -rf .github
          ls -alF
          git clone ${{secrets.GIT_ADDRESS1}} .
        shell: bash
      
      - name: install
        run: npm i
      
      - name: build
        run: npm run build

      - name: get package version
        id: package
        uses: Ireoo/get-package@v1
        with:
          path: ./package.json
          key: version
    
      - name: get package productName
        id: package1
        uses: Ireoo/get-package@v1
        with:
          path: package.json
          key: productName
          
      - name: create release
        id: release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: v${{steps.package.outputs.version}}
          release_name: V${{steps.package.outputs.version}}
          draft: false
          prerelease: false
    
#       - name: init cache
#         id: cache
#         shell: bash
#         env:
#           git_cache: ${{secrets.GIT_CACHE}}
#           github_sha: ${{github.sha}}
#         run: |
#           git clone $git_cache cache
#           cd cache
#           echo "::set-output name=upload_url::$(cat $github_sha.txt)"
          
      - name: Upload Release
        uses: Ireoo/upload-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          dir: build
          exts: '["exe", "dmg", "zip", "appimage", "deb", "rpm", "apk", "msi", "pkg", "appx"]'
          suffix: '_v${{steps.package.outputs.version}}'
